
volumes:
    uploads:
        driver: local
    logs:
        driver: local

networks:
    app_net:

services:
    ospos-mysql:
        image: mariadb:10.5
        container_name: ospos-mysql
        restart: always
        expose:
          - "3306"
        networks:
          - app_net
        volumes:
          - ./data/database/db:/var/lib/mysql:rw
        environment:
          - MYSQL_ROOT_PASSWORD=pointofsale
          - MYSQL_DATABASE=ospos
          - MYSQL_USER=admin
          - MYSQL_PASSWORD=pointofsale
